name: CI Workflow
on:
  pull_request:
    branches:
      - master
      - release-*
  workflow_dispatch: {}

defaults:
  run:
    working-directory: go/src/sigs.k8s.io/work-api

env:
  # Common versions
  GO_VERSION: 1.17.x
  GO_PATH: '/home/runner/work/work-api/work-api/go'

jobs:
  detect-noop:
    runs-on: ubuntu-latest
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v3.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.mdx", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
          concurrent_skipping: false

#  verify:
#    name: verify
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout code
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 1
#          path: go/src/sigs.k8s.io/work-api
#
#      - name: install Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: ${{ env.GO_VERSION }}
#
#      - name: verify
#        run: hack/verify-all.sh -v
#        env:
#          GOPATH: ${{ env.GO_PATH }}

  test:
    name: unit test
    runs-on: ubuntu-latest
    if: needs.detect-noop.outputs.noop != 'true'
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/sigs.k8s.io/work-api

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: make test
        run: make test
        env:
          GOPATH: ${{ env.GO_PATH }}

      - name: Upload report
        uses: codecov/codecov-action@v2.1.0
        with:
          ## Repository upload token - get it from codecov.io. Required only for private repositories
          token: ${{ secrets.CODECOV_TOKEN }}
          ## Comma-separated list of files to upload
          files: ./cover.out
          flags: ci-tests
          name: codecov-umbrella

  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/sigs.k8s.io/work-api
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: images
        run: make docker-build
        env:
          GOPATH: '/home/runner/work/work-api/work-api/go'
      - name: setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
      - name: Load image on the nodes of the cluster
        run: |
          kind load docker-image --name=kind work-api-controller:latest
      - name: Run e2e test
        run: |
          make test-e2e
        env:
          KUBECONFIG: /home/runner/.kube/config